### PR TITLE
Feature migrations to oscar 2

### PR DESCRIPTION
**Pull request by dfirst**
1. Update to oscar 2.0.
2. Update sandbox.
3. Add test app.
4. Bug fixes + tests.

### CODE REVIEW

**Comment by solarissmoke** [comment]
@dfirst could I request that you revert the change that applies `black` here? There are two reasons for this:

1. it makes it very difficult to see what code has actually changed. Even if we do apply it, it should be a separate commit.

2. Black is extremely opinionated, and only makes sense to use if we decide to enforce it on the repository going forward. That is a decision that I think the other maintainers need to weigh in on.

**Comment by dfirst** [comment]
@solarissmoke done

**Comment by laevilgenius** [comment]
I'm getting `ModuleNotFoundError` on this line:
```python
self.home_view = get_class('oscar_promotions.views', 'HomeView')
```
I think it's due to `module_prefix='oscar.apps'` in `get_class`/`get_classes` functions.

Simply setting it to the empty string doesn't help as `default_class_loader` doesn't expect empty `module_prefix`.

**Comment by solarissmoke** [comment]
@laevilgenius is this with the sandbox in this repo, or in your own project that you're running with this branch?

**Comment by laevilgenius** [comment]
@solarissmoke, own project, while trying to migrate to oscar 2.

**Comment by dfirst** [comment]
@laevilgenius 
This issue related to all the oscar 3rd packages, I fixed this issue by tweaking get_class method for 3rd party oscar apps.

**Comment by solarissmoke** [comment]
Hmm, the new class loader _should_ in theory work with third party apps, if we supply the right `module_prefix` when calling get_class here. If it doesn't, I think we need to import the views directly instead of using `get_class`.

**Comment by laevilgenius** [comment]
The right `module_prefix` would probably be an empty string which would lead to invalid `oscar_module_label` in `default_class_loader`:
```python
oscar_module_label = "%s.%s" % (module_prefix, module_label)
```
So we may need to change `default_class_loader` slightly.

**Comment by dfirst** [comment]
@solarissmoke 
Yes as @laevilgenius mentioned for 3rd packages empty `module_prefix` solving problem but i think some general solution would be good. Because extensible packages is good thing to have.

**Comment by solarissmoke** [comment]
Yeah, I think you're right. I would suggest that for now we don't do dynamic class loading here - until we've fixed this in Oscar - and then we can update this package.

**Comment by solarissmoke** [comment]
Having looked at this again, it seems to me the way to resolve this is to specify the module prefix when loading classes - i.e. `get_class('...', '...', module_prefix='oscar_promotions')`. That should ensure that fallback loading happens from this package.

**Comment by solarissmoke** [comment]
Closing in favour of #6 which incorporates these changes and finishes off changes required for Oscar 2 support.

**Pull request closed without merging**
